### ISSUE TITLE
Provide mechanism to turn off editorconfig rules for some files

### ISSUE THREAD

**Issue by mcandre** [slang800/editorconfig-tools#11]
As a Lisper, I want editorconfig-tools to check for two space `indent_size` for most files, while ignoring `indent_size` for Lisp files (`.lisp`, `.lsp`, `.clj`, `.el`).

For example, editorconfig for Emacs uses `none` to accomplish this. https://github.com/editorconfig/editorconfig/issues/187

Occasionally, command line traces placed in *.md files also trigger indentation warnings; it would be nice to be able to make exceptions for *.md, *.html, and other documentation files.

**Comment by slang800** [comment]
you can set / [unset](https://github.com/editorconfig/editorconfig/issues/165) all those values in your editorconfig file. just going off of what you wrote, I think it would look like this:

```editorconfig
[*]
indent_size = 2
indent_style = space

[*.{lisp,lsp,clj,el,md,html}]
indent_size = none
```
Setting it to none/null should make it ignore that setting, for those particular file types.

**Comment by mcandre** [comment]
Ideally, but editorconfig-tools v0.0.1 isn't parsing `none` correctly.

```
$ cat .editorconfig
[*]
indent_style = space
indent_size = 2

[{*.lisp,*.scm,*.rkt,*.lsp,*.clj,*.el}]
indent_size = none

$ cat hello.lisp 
#!/usr/bin/env sh
#|
exec clisp -q -q $0 $0 ${1+"$@"}
|#

(defun hello-main (args)
  (format t "Hello from main!~%"))

;;; With help from Francois-Rene Rideau
;;; http://tinyurl.com/cli-args
(let ((args
       #+clisp ext:*args*
       #+sbcl sb-ext:*posix-argv*
       #+clozure (ccl::command-line-arguments)
       #+gcl si:*command-args*
       #+ecl (loop for i from 0 below (si:argc) collect (si:argv i))
       #+cmu extensions:*command-line-strings*
       #+allegro (sys:command-line-arguments)
       #+lispworks sys:*line-arguments-list*
     ))

  (if (member (pathname-name *load-truename*)
              args
              :test #'(lambda (x y) (search x y :test #'equalp)))
    (hello-main args)))

$ editorconfig-tools check hello.lisp 
hello.lisp failed indent_char: found setting '  ', should be 'none1'
```

**Comment by slang800** [comment]
oh, that's very wrong... try `0.1.0`, I just published it now

**Comment by mcandre** [comment]
Same problem exists in editorconfig-tools@0.1.0 :(

**Comment by mcandre** [comment]
Thanks for working on this! Overall, I'm really happy with editorconfig-tools!

Could we publish a bugfix version for this, say `0.1.1`?

**Comment by slang800** [comment]
done!

if this were past major version 0, that would actually be a major version bump because I changed the `Rule` constructor's return value to a promise and if someone was using the JS API it would break. But since that API is undocumented and this is still at v0, I'm alright with just patching.

**Comment by mcandre** [comment]
Good news: v0.1.1 fixes this issue for 99% of my code.

Bad news: `profiles.clj` is still triggering a false positive somehow.

Configuration:

```
[*]
indent_size = 2

[{*.lisp,*.scm,*.rkt,*.lsp,*.clj,*.el}]
indent_size = none
```

Code:

```
$ cat profiles.clj 
;; ln .../profiles.clj ~/.lein/profiles.clj

{:user {:plugins [[lein-exec "0.3.0"]
                  [jonase/eastwood "0.0.2"]]}}
```

Trace:

```
$ node_modules/editorconfig-tools/bin/index.js check profiles.clj 
profiles.clj failed indent_char: found setting '                  ', should be '  '
```

**Comment by slang800** [comment]
oh, that's an issue caused by the way that [detect-indent](https://github.com/sindresorhus/detect-indent) works. it looks for the most common difference between 2 consecutive lines, and since that file is so short, an 18 char indent is all that it sees.

I could sacrifice support of 18-char indentation by skipping files that report having that much indentation and assuming it's a false result, or maybe I could skip files that have very few lines?

Neither of these are perfect, and they don't address the underlying issue with the ambiguity of detecting indentation settings for files that also have alignment done using leading white-space.

**Comment by mcandre** [comment]
My .editorconfig specifies *none* for .clj files, so detect-indent
shouldn't even be executed for profile.clj.

On Thu, Mar 5, 2015 at 9:44 AM, Sean Lang <notifications@github.com> wrote:

> oh, that's an issue caused by the way that detect-indent
> <https://github.com/sindresorhus/detect-indent> works. it looks for the
> most common difference between 2 consecutive lines, and since that file is
> so short, an 18 char indent is all that it sees.
>
> I could sacrifice support of 18-char indentation by skipping files that
> report having that much indentation and assuming it's a false result, or
> maybe I could skip files that have very few lines?
>
> Neither of these are perfect, and they don't address the underlying issue
> with the ambiguity of detecting indentation settings for files that also
> have alignment done using leading white-space.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slang800/editorconfig-tools/issues/11#issuecomment-77387035>
> .
>



-- 
Cheers,

Andrew Pennebaker
www.yellosoft.us
