### ISSUE TITLE
On windows, wild cards are not supported while using editorconfig-tools

### ISSUE THREAD

**Issue by 210178** [slang800/editorconfig-tools#40]
I am getting the following error when I run the command : editorconfig-tools check ./.env app/**/

Error:
fs.js:941
  binding.lstat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, lstat 'C:\work\receive\app\**\*.js'

But the same command works fine in mac :-( 

Please help me how can I fix this to work on both windows and mac

**Comment by notslang** [comment]
I don't know much about Windows, but I don't think that it supports globbing: https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths

**Comment by notslang** [comment]
You could try installing [Cygwin](https://cygwin.com/index.html). IIRC that will give you the ability to run bash on Windows.
